name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  containerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the container image
      run: docker build ./player --file ./player/Dockerfile --tag player-image:latest
    - uses: anchore/scan-action@v2
      with:
        image: "player-image:latest"
        fail-build: false
        debug: true
        acs-report-enable: true
    - name: grype scan JSON results
      run: cat results.sarif; cat vulnerabilities.json; for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
      
  sonarqube:
    environment: pipeline-environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        projectBaseDir: /player
        args: >
          -Dsonar.projectKey=player
          -Dsonar.verbose=true
          
  DAST:
    environment: pipeline-environment
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: echo "This is the cmd test \n\n\n\n\n\n\n\n\n\n"
#            echo "cmd test"
#            ls -a
#            cd /tmp
#            ls -a
#            exit 1
          host: ${{ secrets.TEST_ENV_AKA_LRS_EC2 }}
          user: ubuntu
          key: ${{ secrets.EC2_LRS_PEM }}
          args: "-v"
        
